DeployToTestfordemo:
 stage: deploy
 only: ["master", "Public"]
 tags: ["public", "testing", "taiwan"]
 script:
   - cd /opt/www/arcweb_lv && git checkout . && git pull && chown -R www-data:www-data *
   - docker exec -t $(docker ps | grep node  | awk '{print $1}') ash -c "pm2 reload 0"

DeployToProduction:
 stage: deploy
 only: ["Production"]
 tags: ["nginx", "production"]

 script:
   - cd /opt/www/arcweb_lv && git checkout . && git pull origin Production && chown -R www-data:www-data *
   - docker exec -t $(docker ps | grep node  | awk '{print $1}') ash -c "pm2 reload 0"


variables:
  GIT_STRATEGY: none
