DeployToTestfordemo:
 stage: deploy
 only: ["master", "Public"]
 tags: ["public", "testing", "taiwan"]
 script:
   - cd /opt/www/arcweb_lv && git checkout . && git pull && chown -R www-data:www-data *

DeployToProduction:
 stage: deploy
 only: ["Production"]
 tags: ["nginx", "production"]

 script:
   - cd /opt/www/arcweb_lv && git checkout . && git pull origin Production && chown -R www-data:www-data *


variables:
  GIT_STRATEGY: none
