DeployToTestfordemo:
 stage: deploy
 only: ["master", "Public"]
 tags: ["public", "testing", "taiwan"]
 script:
   - cd /opt/www/arcweb_lv && git pull && chown -R www-data:www-data *
   - docker exec -t $(docker ps | grep node  | awk '{print $1}') ash -c "cd /opt/www/arcweb_lv/ && npm install && npm run build"
   - docker exec -t $(docker ps | grep node  | awk '{print $1}') ash -c "pm2 reload index"

DeployToProduction:
 stage: deploy
 only: ["Production"]
 tags: ["nginx", "production"]

 script:
   - cd /opt/www/arcweb_lv && git pull && chown -R www-data:www-data *
   - docker exec -t $(docker ps | grep node  | awk '{print $1}') ash -c "cd /opt/www/arcweb_lv/ && npm install && npm run build"
   - docker exec -t $(docker ps | grep node  | awk '{print $1}') ash -c "pm2 reload index"


variables:
  GIT_STRATEGY: none
